name: 'Automatically Manage Stale Issues and PRs'
permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been marked as stale due to 14 days of inactivity. Please remove the stale label or comment to keep it open, otherwise, it will be closed in 3 days.'
          stale-pr-message: 'This pull request has been marked as stale due to 7 days of inactivity. Please remove the stale label or comment to keep it open, otherwise, it will be closed in 3 days.'
          close-issue-message: 'This issue was closed due to 3 additional days of inactivity after being marked as stale.'
          close-pr-message: 'This pull request was closed due to 3 additional days of inactivity after being marked as stale.'
          days-before-issue-stale: 21
          days-before-pr-stale: 21
          days-before-issue-close: 7
          days-before-pr-close: 7
